server:
    port: 4000
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/godlife?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
    security:
        oauth2:
            client:
                provider:
                    naver:
                        user-name-attribute: response
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 요청 uri
                        token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 발급받기 위한 uri
                        user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 정보를 받아오기 위한 uri
                registration:
                    naver:
                        client-id: KdXAxHFq5g2ginpsMAqY
                        client-secret: 53Xh1Q2t5P
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                        - email
                        - nickname