server:
    port: 4000
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://soogwang-mysql.cpqi0gk60m23.ap-northeast-2.rds.amazonaws.com/godlife?serverTimezone=UTC&characterEncoding=UTF-8
        username: admin
        password: P!ssw0rd
    security:
        oauth2:
            client:
                provider:
                    naver:
                        user-name-attribute: response
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 요청 uri
                        token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 발급받기 위한 uri
                        user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 정보를 받아오기 위한 uri
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                registration:
                    naver:
                        client-id: KdXAxHFq5g2ginpsMAqY
                        client-secret: 53Xh1Q2t5P
                        authorization-grant-type: authorization_code
                        redirect-uri: "https://api.godlife.co.kr/oauth2/callback/{registrationId}"
                        scope:
                        - email
                        - nickname
                    kakao:
                        client-name: Kakao
                        client-id: 27c00b69d2af490f7d98544ae6419081
                        client-authentication-method: POST
                        authorization-grant-type: authorization_code
                        redirect-uri: "https://api.godlife.co.kr/oauth2/callback/{registrationId}"
                        scope: profile_nickname, account_email
                    google:
                        client-id: 1086638355618-ljquj432r6ubakahtg1bnammsbt8monp.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: "https://api.godlife.co.kr/oauth2/callback/{registrationId}"
                        scope:
                        - email
                        - profile